name: Build C++ EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2

      - name: Build EXE
        run: g++ main.cpp -o main.exe -static -static-libgcc -static-libstdc++

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: main-exe
          path: main.exe
