name: Build C++ EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check files
        run: dir

      - name: Build
        run: g++ main.cpp -o main.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: main-exe
          path: main.exe
